### ISSUE TITLE
Make it very hard to plot TE, EE and BB theory curves

### ISSUE THREAD

**Issue by msyriac** [simonsobs/psplay#3]
I worry that the default settings here make it way too easy to accidentally unblind our data. Since the whole point of this (amazing) software is exploratory analysis of data, could I recommend that you make it very hard to plot TE, EE and BB theory curves? The option should ideally be hidden away somewhere, and if toggled, it should show a bunch of warnings and "are you sure?"s.

**Comment by xgarrido** [comment]
PR #4 should adress this issue. By default, only TT spectrum from theory is plotted. It is still possible to show other spectra but user must allow them in the `yaml` file with such syntax

```yaml
  theory:
    file: bode_almost_wmap5_lmax_1e4_lensedCls_startAt2.dat
    allow: [TT, TE, EE, BB]
```
